apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpose-deployment
  labels:
    app: cloudpose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudpose
  template:
    metadata:
      labels:
        app: cloudpose
    spec:
      nodeSelector:
        kubernetes.io/hostname: izj6c1ctx7gdveo620l4paz
      containers:
      - name: cloudpose
        image: cloudpose:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 60000
        resources:
          requests:
            cpu: "1.0"
            memory: "1Gi"
          limits:
            cpu: "2.0"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 60000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5 