apiVersion: v1
kind: Service
metadata:
  name: cloudpose-service
  labels:
    app: cloudpose
spec:
  type: NodePort
  selector:
    app: cloudpose
  ports:
  - name: http
    port: 60000
    targetPort: 60000
    nodePort: 30000
    protocol: TCP 